export type DTReportItemSimple = {
	"Legal Name": string,
	"DBA Name": string,
	"Street": string,
	"City": string,
	"State": string,
	"Zip": string | number,
	"Country": string,
	"Phone No": bigint | string | number,
	"Fax No"?: bigint | string | number,
	"User Count": number,
	"DealerTrack Id": number,
	"Lender Dealer Id": number | bigint | string,
	"Lender Rep Name": string,
	"Lender Rep Id": string,
	"Enrollment Date": string,
	"Agreement Received": string,
	"Enrollment Phase": string,
	"Enrollment Update Date": string,
	"Modified Date": string,
	"Status": "A" | "I",
}

export type DTReportItem = DTReportItemSimple & {
	"Dept": string,
	"Alternate Street": string,
	"Independent": string,
	"PaymentTrack Id": string,
	"Equifax Signup Date": string,
	"Transunion Signup Date": string,
	"Experian Reseller Signup Date": string,
	"Experian Direct Signup Date": string,
	"Cost Center": string,
	"Loan App Id": string,
	"Lease App Id": string,
	"Loan Svc Id": string,
	"Lease Svc Id": string,
	"Prime Id": string,
	"Subprime Id": string,
	"Subvented Id": string,
	"Match Change Date": string,
	"Previous Match Dealerid": string | number,
	"Grace Period Status": string,
	"Agreement Required By Date": string,
	"Agreement Version": string,
	"Agreement Signatory": string,
	"Overall Use 30 Days": string,
	"Equifax Status": string,
	"Experian Status": string,
	"Transunion Status": string,
	"PaymentTrack Status": string,
	"eContract Status": string,
	"Dealer File Override": string,
	"Override Expiration": string,
	"Vehicle Type": string,
	"Created Date": string,
	"Activated Date": string,
	"Equifax Use 30 Days": string,
	"Experian Use 30 Days": string,
	"Transunion Use 30 Days": string,
	"DMS Use 30 Day": string,
	"DMS Status": string,
	"BookOut Kelley Status": string,
	"BookOut Kelley 30 Day Activity": string,
	"BookOut NADA Status": string,
	"BookOut NADA 30 Day Activity": string,
	"BookOut Black Status": string,
	"BookOut Black 30 Day Activity": string,
	"SalesDesk Status": string,
	"SalesDesk 30 Day Activity": string,
	"BookOut Pro Status": string,
	"BookOut Pro 30 Day Activity": string,
	"EFTFAX": string,
	"eMenu Status": string,
	"eMenu Version": string,
	"eMenu 30 Day Activity": string,
	"Independent Preference": string,
	"Independent Status": string,
	"Independent 30 Day Activity": string,
	"Notes": string,
	"uniFI Indicator": string,
}
